
<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="add"
		action='erp_masters/building/add' style="margin-bottom: 0px;">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Add Building</h4>
		</div>

		<div class="modal-body">
			<div class="form-group row" style="margin-top: 15px;">
				<label class="col-sm-2 form-control-label">Name</label>
				<div class="col-sm-5">
                    <?=$this->form->bld_name->show()?>
                  </div>

				<label class="col-sm-1 form-control-label">No.</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_no->show()?>
                  </div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label">Area</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_area->show()?>
                  </div>

				<label class="col-sm-2 form-control-label">Block No.</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_block_no->show()?>
                  </div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label">Plot</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_plot_no->show()?>
                  </div>
				<label class="col-sm-2 form-control-label">Way</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_way->show()?>
                  </div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label">Street</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_street->show()?>
                  </div>
				<label class="col-sm-2 form-control-label">Block Name</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_block->show()?>
                  </div>
			</div>
		</div>
		<div class="modal-footer popup-footer">
			<button type="button"
				class="btn btn  btn-success submit-alias btn-rounded livepost">Add</button>
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</form>
</div>

<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '700px');
})
</script>

