<div class="dynamic-popup" id="dynamic-popup">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Building Details</h4>
	</div>

	<div class="modal-body">
		<div class="form-group row" style="margin-top: 15px;">
			<label class="col-sm-2 form-control-label">Name</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_name']?>
                  </div>

			<label class="col-sm-2 form-control-label">No.</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_no']?>
                  </div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 form-control-label">Area</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_area']?>
                  </div>

			<label class="col-sm-2 form-control-label">Block No.</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_block_no']?>
                  </div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 form-control-label">Plot</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_plot_no']?>
                  </div>
			<label class="col-sm-2 form-control-label">Way</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_way']?>
                  </div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 form-control-label">Street</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_street']?>
                  </div>
			<label class="col-sm-2 form-control-label">Block Name</label>
			<div class="col-sm-4">
                    <?=$this->buildingDetail['bld_block']?>
                  </div>
		</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '550px');
})
</script>
