<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" name="edit" action='admin/users/add'>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Add New Member</h4>
	</div>
<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >First
						Name</label>
					<div class="col-sm-9">
                    <?=$this->form->fname->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Last
						Name</label>
					<div class="col-sm-9">
                    <?=$this->form->lname->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >User
						Name</label>
					<div class="col-sm-9">
                    <?=$this->form->uname->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Password
						</label>
					<div class="col-sm-9">
                    <?=$this->form->password->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Role</label>
					<div class="col-sm-9">
                    <?=$this->form->desig->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Status</label>
					<div class="col-sm-9">
                    <?=$this->form->status->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Add</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>


<script type="text/javascript">           
$(document).ready(function() {

	typetoggle($('#type').val());

	$('#type').on('change',function() {
		typetoggle($(this).val());
	});
	function typetoggle(type){
		if(type==2)
			$('#login_det').show();
		else
			$('#login_det').hide();
	}
});
</script>
