<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" name="edit" action='admin/users/branch/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Update contact details</h4>
	</div>
<div class="modal-body">
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Branch</label>
					<div class="col-sm-9">
                    <?=$this->form->branch->show()?>
                  </div>
				</div>
				</div>	
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>
