<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_manage/updates/add/ref/<?=$this->param['ref']?>/type/<?=$this->param['type']?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Notes / Updates
		</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >Priority</label>
					<div class="col-sm-9">
                    <?=$this->form->priority->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Title</label>
					<div class="col-sm-9">
                    <?=$this->form->title->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Description</label>
					<div class="col-sm-9">
                    <?=$this->form->desc->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Date of Event</label>
					<div class="col-sm-9">
                    <?=$this->form->startDt->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Expected end Date</label>
					<div class="col-sm-9">
                    <?=$this->form->endDt->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>

