<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_fund/cashbook/add' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Personnel Cash Book Debit Details</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-2 form-control-label" >Date</label>
					<div class="col-sm-4">
                    <?=$this->form->debitdt->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Debit Amount</label>
					<div class="col-sm-4">
                    <?=$this->form->amount->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Note</label>
					<div class="col-sm-10">
                    <?=$this->form->note->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Add</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<style>
.modal-dialog{
	width: 60%;
}
</style>
