<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_employee/salary/emppayedit/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Update Pay details</h4>
	</div>
	<div class="modal-body">
			<div class="form-group row">
				<label class="col-sm-2 form-control-label" >Pay Particulers</label>
					<div class="col-sm-2">
                    <?=$this->form->paytran->show()?>
                  </div>
				<label class="col-sm-2 form-control-label" >Basic Pay</label>
					<div class="col-sm-2">
                    <?=$this->form->bp->show()?>
                  </div>
				<label class="col-sm-2 form-control-label" >DA</label>
					<div class="col-sm-2">
                    <?=$this->form->da->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >HRA</label>
					<div class="col-sm-2">
                    <?=$this->form->hra->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >TA</label>
					<div class="col-sm-2">
                    <?=$this->form->ta->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Other Allowance 1</label>
					<div class="col-sm-2">
                    <?=$this->form->all1->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Other Allowance 2</label>
					<div class="col-sm-2">
                    <?=$this->form->all2->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Other Allowance 3</label>
					<div class="col-sm-2">
                    <?=$this->form->all3->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >With effect from</label>
					<div class="col-sm-2">
                    <?=$this->form->wef_e->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Next Revision</label>
					<div class="col-sm-2">
                    <?=$this->form->dor_e->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Remarks</label>
					<div class="col-sm-6">
                    <?=$this->form->remark->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<script type="text/javascript">           
$(document).ready(function() {
	initDatePicker();
});
</script>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '80%');
})
</script>
