<?php
require_once "../action/_documents.php";
$ref = filter_input ( INPUT_GET, 'ref', FILTER_SANITIZE_STRING );
$var = doc_status($ref);

$formRender = $var['formRender'];
$expenseDet = $var['expenseDet'];
$form = $var['form'];

if ($formRender):?>
<?php if($expenseDet['exp_app_status']==''):?>
<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='<?=APPURL?>updates/status/ref/<?=$ref?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Update Status
		</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >Status</label>
					<div class="col-sm-9">
                    <?=$this->form->status->show()?>
                  </div>
				</div>
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >Note</label>
					<div class="col-sm-9">
                    <?=$this->form->note->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Approve</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<?php endif?>
<?endif?>
