<div class="dynamic-popup" id="dynamic-popup"><!--  -->
<form name="docform" method="post" id="docform" action="erp_expense/expense/catedit/ref/<?=$this->param['ref'];?>"	style="margin-bottom: 0px;" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Update Category</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-4 form-control-label" >Parent Category
						</label>
					<div class="col-sm-6">
                    <?=$this->form->pCatSelect->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4 form-control-label" >Sub Category
						</label>
					<div class="col-sm-6">
                    <?=$this->form->sCatSelect->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4 form-control-label" >Child Category
						</label>
					<div class="col-sm-6">
                    <?=$this->form->cCatSelect->show()?>
                  </div>
				</div>
				<div class="form-group row">
				<label class="col-sm-4 form-control-label" >Particulers</label>
					<div class="col-sm-6">
					<?=$this->form->particulers->show()?>
                  </div>
			  	</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<script type="text/javascript">           
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'erp_expense/expense/getlive';
	$('#pCatSelect').on('change',function() {
		getJaxData($('#pCatSelect').val(),'sCatSelect',source,'parent');
		$('#cCatSelect').empty();
	});
	getJaxData($('#pCatSelect').val(),'sCatSelect',source,'parent');

	$('#sCatSelect').on('change',function() {
		getJaxData($('#sCatSelect').val(),'cCatSelect',source,'sub');
	});
	getJaxData($('#sCatSelect').val(),'cCatSelect',source,'sub');


});
</script>

<style>
.modal-dialog{
	width: 50%;
}
</style>
