<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" name="edit" action='erp_vehicle/master/vhldocsedit/ref/<?=$this->param['ref'];?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Modify Documet Details</h4>
	</div>
	<div class="modal-body">		
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-2 form-control-label" >Document No.</label>
					<div class="col-sm-4">
                    <?=$this->form->docno->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Description</label>
					<div class="col-sm-4">
                    <?=$this->form->docdesc->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Remarks</label>
					<div class="col-sm-4">
                    <?=$this->form->docremark->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Issue Authority</label>
					<div class="col-sm-4">
                    <?=$this->form->auth->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Date of apply</label>
					<div class="col-sm-4">
                    <?=$this->form->doa->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Date of Issue</label>
					<div class="col-sm-4">
                    <?=$this->form->doi->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Date of expiry</label>
					<div class="col-sm-4">
                    <?=$this->form->doe->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Alert days</label>
					<div class="col-sm-2">
                    <?=$this->form->alert->show()?>
                  </div>
				</div>
			<div class="form-group row">
				<div id="" class="col-sm-3">
					<div class="">
						<label class="form-control-label">Upload Document <?=$this->form->docUpdate->show()?></label>
	                     
	                  </div>
				</div>
				<div class="col-sm-4" style="margin-left:  -80px;">
					<div id="docUpload">
                 		<?=$this->form->my_files->show()?>
                 	</div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>

<script type="text/javascript">           
$('#docUpdate1').on('click',function() {
	typetoggle();
});
typetoggle();
function typetoggle(type){
	if($('#docUpdate1').prop('checked') === true)
		$('#docUpload').show();
	else
		$('#docUpload').hide();
}
</script>

<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '70%');
})
</script>

