<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_employee/master/empdocsedit/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Modify Document Details</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">				
				
					<label class="col-sm-2 form-control-label" >Document Type</label>
					<div class="col-sm-4">
                    <?=$this->form->doctype->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Document No.</label>
					<div class="col-sm-4">
                    <?=$this->form->docno->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Description</label>
					<div class="col-sm-4">
                    <?=$this->form->docdesc->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Remarks</label>
					<div class="col-sm-4">
                    <?=$this->form->docremark->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Issue Authority</label>
					<div class="col-sm-4">
                    <?=$this->form->auth->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Date of apply</label>
					<div class="col-sm-4">
                    <?=$this->form->doa->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Date of Issue</label>
					<div class="col-sm-4">
                    <?=$this->form->doi->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Date of expiry</label>
					<div class="col-sm-4">
                    <?=$this->form->doe->show()?>
                  </div>
				</div>
				<div class="form-group row">
					
	                  <div id="" class="col-sm-4">
	                  <label class="form-control-label" >Upload Document</label>
	                     <?=$this->form->docUpdate->show()?>
                  	  </div>
                  	  <div  class="col-sm-3">
                  	  <div id="docUpload">
                     		<?=$this->form->my_files->show()?>
                     	</div>
	                  </div>
                  	  

					<label class="col-sm-2 form-control-label" >Alert days</label>
					<div class="col-sm-2">
                    <?=$this->form->alert->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>

<script type="text/javascript">           
$('#docUpdate1').on('click',function() {
	typetoggle();
});
typetoggle();
function typetoggle(type){
	if($('#docUpdate1').prop('checked') === true)
		$('#docUpload').show();
	else
		$('#docUpload').hide();
}
</script>

<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '80%');
})
</script>

