<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Leave Details</h4>
	</div>
	<div class="modal-body">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th class="center" width="25%">Remarks</th>
					<th class="center" width="12%">Effect From</th>
					<th class="center" width="12%">Return Approved</th>
					<th class="center" width="12%">Rejoin Date</th>
					<th class="center" width="12%">Leave Sanctioned</th>
					<th class="center" width="12%">Leave Taken</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->leaveDetail as $leave):?>
				<tr>
					<td><?=$leave['sts_remarks']?></td>
					<td align="center"><?=$leave['leave_start']?></td>
					<td align="center"><?=$leave['leave_end']?></td>
					<td align="center"><?=$leave['date_return']?></td>
					<td align="center"><?=$leave['days_sanctioned']?></td>
					<td align="center"><?=$leave['days_taken']; @$leaveTaken+=$leave['days_taken'];?></td>										
				</tr>
			<?php endforeach;?>
				<tr>
					<td align="right" colspan="5"><b>Total Leave Days</b></td>
					<td align="center" ><b><?=$leaveTaken?></b></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '70%');
})
</script>
