<?$offset = $this->empObj->_voffset;?>
<div class="card-block" style="padding-top: 2%;">
	<div class="full-width">
		<?=x(array('link'=>'erp_employee/master/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')),'<br><br>')?>
	</div>
	<h5 class="title-margin">&nbsp;&nbsp;&nbsp;List of Employees</h5>
</div>
<form method="get" id="filter" name="filter" action="">
<div class="col-md-12 card filter-card">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="6%">File</th>
				<th width="18%">Name</th>
				<th width="3%">Company</th>
				<th width="9%">Department</th>
				<th width="9%">Designation</th>
				<th width="9%">Nationality</th>
				<th width="5%">Status</th>
				<th width="15%">

				</th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_fileno->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_name->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_company->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_dept->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_desig->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_natonality->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_status->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
	              	<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>

<div class="col-md-12">
	<div class="card">
		<table class="table table-bordered grid">
			<thead>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="5%" class="center">File No</th>
					<th width="15%" class="center">Name</th>
					<th width="7%" class="center">Company</th>
					<th width="15%" class="center">Department</th>
					<th width="12%" class="center">Designation</th>
					<th width="10%" class="center">Contact</th>
					<th width="10%" class="center">Status</th>
					<th width="10%" class="center">Edit</th>
					<th width="6%" class="center">View</th>
					<!--  <th width="6%" class="center">Delete</th>-->
				</tr>
			</thead>
			<tbody>
			<?if(count($this->employeeList)>0):?>
				<?php foreach($this->employeeList as $employee):
					$encEmpId = $this->encode($employee['emp_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$employee['emp_fileno']?></td>
					<td><?=$employee['emp_fname']?>&nbsp;<?=$employee['emp_mname']?>&nbsp;<?=$employee['emp_lname']?></td>
					<td><?=$employee['comp_disp_name']?></td>
					<td><?=$employee['dept_name']?></td>
					<td><?=$employee['desig_name']?></td>
					<td class="center"><?//=$nation[$employee['emp_nationality']]?><?=$employee['emp_mobileno']?></td>
					<td class="center"><?php if(!$employee['emp_mstatus']):?> Active <?php else:?> <?=$employee['emp_mstatus']?> <?php endif;?>
						<?=x(array('link'=>'erp_employee/master/status','ref'=>array('ref'=>$encEmpId),'label'=>'<i class="glyphicon glyphicon-edit text-info"></i>',array("param"=>'class="facebox"')))?></td>
						  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_employee/master/edit','ref'=>array('ref'=>$encEmpId),'label'=>'<i class="glyphicon glyphicon-edit text-info"></i>',array("param"=>'class="facebox"')))?>  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_employee/master/view','ref'=>array('ref'=>$encEmpId),'label'=>'<i class="glyphicon glyphicon-search text-info"></i>'))?> 
					</td>
					<!--<td class="center">
						<?//=x(array('link'=>'employee/delete','ref'=>$encEmpId,'label'=>'<i class="glyphicon glyphicon-trash text-danger"></i>',array("param"=>'class="facebox"')))?> 
					</td>-->
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->empObj->pagination();?>
	</div>
</div>
</form>

	<?=x(array('link'=>'erp_report/employee/employee','label'=>'
			<div class="col-md-3">
				<div class="card">
						<div class="card-block">
						<div class="card-block">
							<h4 class="card-title center">Employees</h4>
							<p class="card-text">
								<small class="text-muted"></small>
							</p>
						</div>
					</div>
				</div>
			</div>
		', array("param"=>'wide_opener')),'<br><br>')?>
	<?=x(array('link'=>'erp_report/employee/empdocument','label'=>'
		<div class="col-md-3">
			<div class="card">
					<div class="card-block">
					<div class="card-block">
						<h4 class="card-title center">Emp Document</h4>
						<p class="card-text">
							<small class="text-muted"></small>
						</p>
					</div>
				</div>
			</div>
		</div>
	', array("param"=>'wide_opener')),'<br><br>')?>
	
	<?=x(array('link'=>'erp_report/employee/empdocument/ref/exp','label'=>'
		<div class="col-md-3">
			<div class="card">
					<div class="card-block" style="background-color: ;">
					<div class="card-block">
						<h4 class="card-title center">Emp. Doc. Expiry</h4>
						<p class="card-text">
							<small class="text-muted"></small>
						</p>
					</div>
				</div>
			</div>
		</div>
	', array("param"=>'wide_opener')),'<br><br>')?>
		
	<?=x(array('link'=>'erp_report/employee/empcontract','label'=>'
		<div class="col-md-3">
			<div class="card">
					<div class="card-block" style="background-color: ;">
					<div class="card-block">
						<h4 class="card-title center">Operator Status </h4>
						<p class="card-text">
							<small class="text-muted"></small>
						</p>
					</div>
				</div>
			</div>
		</div>
	', array("param"=>'wide_opener')),'<br><br>')?>


<script type="text/javascript">           
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'erp_employee/master/getlive';
	$('#f_company').on('change',function() {
		getJaxData($('#f_company').val(),'f_dept',source);
	});
	getJaxData($('#f_company').val(),'f_dept',source);
});
</script>
