<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_employee/master/status/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
	
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Employee Status
		</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >Status</label>
					<div class="col-sm-9">
                    <?=$this->form->statusType->show()?>
                  </div>
				</div>
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >Description</label>
					<div class="col-sm-9">
                    <?=$this->form->desc->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Date of Request</label>
					<div class="col-sm-9">
                    <?=$this->form->dtRequest->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Date of Approval</label>
					<div class="col-sm-9">
                    <?=$this->form->dtApproval->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >With effect from
						</label>
					<div class="col-sm-9">
                    <?=$this->form->dtWif->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >End Date
						</label>
					<div class="col-sm-9">
                    <?=$this->form->dtEnd->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>

<script type="text/javascript">           
$(document).ready(function() {
	initDatePicker();
	var source = '<?=APPURL?>'+ 'erp_employee/master/getlive';
	$('#company').on('change',function() {
		getJaxData($('#company').val(),'dept',source);
		$("#doi").attr("mindate",$('#doa').val());
		setDatePicker($('#doi'));
		
	});
	getJaxData($('#company').val(),'dept',source);
});
</script>
