<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_masters/customer/add' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Add customer</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-2 form-control-label" >Customer/Company</label>
					<div class="col-sm-4">
                    <?=$this->form->customer->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Name (C/o)</label>
					<div class="col-sm-4">
                    <?=$this->form->name->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Address</label>
					<div class="col-sm-4">
                    <?=$this->form->house->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Street</label>
					<div class="col-sm-4">
                    <?=$this->form->street1->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Place Name</label>
					<div class="col-sm-4">
                    <?=$this->form->place->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Locality</label>
					<div class="col-sm-4">
                    <?=$this->form->locality->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Zip Code</label>
					<div class="col-sm-4">
                    <?=$this->form->zip->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Phone No</label>
					<div class="col-sm-4">
                    <?=$this->form->phone->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Mobile No</label>
					<div class="col-sm-4">
                    <?=$this->form->mobile->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Remarks</label>
					<div class="col-sm-4">
                    <?=$this->form->remarks->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Add</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '70%');
})
</script>
