<?php 
?>
<div class="col-md-12" style="padding-top: 3%;">
	<div class="card">
		<div class="card-block">
			<h5>Company Departments</h5>
			<form name="form" method="post" id="add" name="add" action="">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >Company
						</label>
					<div class="col-sm-9">
                    <?=$this->form->company->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Department
						</label>
					<div class="col-sm-9">
                    <?=$this->form->dept->show()?>
                  </div>
				</div>
				</div>
				<div class="form-group row">
					<div class="col-md-5">
						<button type="submit"
							class="btn  btn-success  btn-block btn-rounded align-button" 
							style="font-size: 120%;">Add</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>


