<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="add" name="add" action="erp_manage/company/edit/ref/<?=$this->param['ref']?>" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title"> &nbsp; Company Documents
		</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-2 form-control-label" >Company
						</label>
					<div class="col-sm-4">
                    <?=$this->form->company->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Document
						</label>
					<div class="col-sm-4">
                    <?=$this->form->doctype->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Document No
						</label>
					<div class="col-sm-4">
                    <?=$this->form->docno->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Details
						</label>
					<div class="col-sm-4">
                    <?=$this->form->docdesc->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Date of Issue
						</label>
					<div class="col-sm-4">
                    <?=$this->form->doi->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Date of Expiry
						</label>
					<div class="col-sm-4">
                    <?=$this->form->doe->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Document
						</label>
					<div class="col-sm-4">
                    <?=$this->form->my_files->show()?>
                  </div>
				</div>
		</div>
    	<div class="modal-footer popup-footer">
    		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
    		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    	</div>
	</div>
</div>
<style>
.modal-dialog{
	width: 75%;
}
</style>
