<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="edit"
		action='erp_property/tenants/edit/ref/<?=$this->param['ref']?>'
		style="margin-bottom: 0px;">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Update Tenant details</h4>
		</div>
		<div class="modal-body">
			<div class="form-group row" style="margin-top: 15px;">
				<label class="col-sm-2 form-control-label">Tenant Type</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_agr_type->show()?>
                  </div>
				<label class="col-sm-2 form-control-label">National/Expart</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_expat->show()?>
                  </div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label">Tenant Name</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_full_name->show()?>
                  </div>
				<label class="col-sm-2 form-control-label">Company Name</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_comp_name->show()?>
                  </div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label">Phone No.</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_phone->show()?>
                  </div>
				<label class="col-sm-2 form-control-label">Mobile No.</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_tele->show()?>
                  </div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label">Id. No.</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_id_no->show()?>
                  </div>
				<label class="col-sm-2 form-control-label">CR. No.</label>
				<div class="col-sm-4">
                    <?=$this->form->tnt_crno->show()?>
                  </div>
			</div>
			<div class="form-group row">
				<label class="col-sm-2 form-control-label">ID Copy</label>
				<div class="col-sm-4">
                    <?=$this->form->my_files->show()?>
                  </div>
				<label class="col-sm-2 form-control-label">CR Copy</label>
				<div class="col-sm-4">
                    <?=$this->form->my_files2->show()?>
                  </div>
			</div>
		</div>
		<div class="modal-footer popup-footer">
			<button type="button"
				class="btn btn  btn-success submit-alias btn-rounded livepost">Update</button>
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</form>
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '700px');
})
</script>
