<div class="card-block" style="padding-top: 2%;">
	<div class="full-width">
		<?=x(array('link'=>'erp_property/master/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')),'<br><br>')?>
	</div>
	<h5 class="title-margin">List of Property</h5>
</div>
<form method="get" id="filter" name="filter" action="list">
<div class="col-md-12 card filter-card">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="10%">File.No</th>
				<th width="10%">Prop No</th>
				<!--  <th width="15%">Name</th>-->
				<th width="25%">Building</th>
				<th width="12%">Category</th>
				<th width="15%">Status</th>
				<th width="15%">Tenant</th>
				<th width="15%"></th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_fileno->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_propno->show()?>
              		</div>
				</td>
				<!--<td>
					<div class="form-group ">
                	<?//=$this->form->f_propname->show()?>
              		</div>
				</td>-->
				<td>
					<div class="form-group ">
                	<?=$this->form->f_building->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_prop_cat->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_prop_status->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_tenant->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>

<div class="col-md-12">
	<div class="card">
		<table class="table table-bordered grid">
			<thead>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="5%" class="center">File No.</th>
					<th width="6%" class="center">Property No</th>
					<th width="10%" class="center">Building Name</th>
					<th width="7%" class="center">Category</th>
					<th width="15%" class="center">Tenant</th>
					<th width="7%" class="center">Level</th>
					<th width="10%" class="center">Status</th>
					<th width="5%" class="center">Rent</th>
					<th width="5%" class="center">Edit</th>
					<th width="5%" class="center">View</th>
					<!--<th width="6%" class="center">Delete</th>-->
				</tr>
			</thead>
			<tbody>
			<?if(count($this->propertyList)>0):?>
				<?php foreach($this->propertyList as $property):
					$encPropId = $this->encode($property['prop_id']);
				?>
								
				<tr>
					<td class="center"><?=@++$this->offset;?></td>
					<td><?=$property['prop_fileno']?> </td>
					<td><?=$property['prop_no']?></td>
					<td><?=$property['bld_name']?></td>
					<td class="center"><? echo $property['prop_cat']==1?"Shop":
					($property['prop_building_type']==1?"Building":"Flat");?></td>
					<td>
					<? if($property['prop_status']==2): ?><? echo $property['agr_tenant']?> <?php endif?></td>
					<td><? echo $this->propLevel[$property['prop_level']]?></td>
					<td class="center" <? if($property['prop_status']==1): ?> style="color:red;font-weight:bold" <?php endif?>><?=$property['property_status']?>
						<?php if($property['prop_building_type']==""):?>
							<?=x(array('link'=>'erp_property/master/status','ref'=>$encPropId,'label'=>'<i class="glyphicon glyphicon-edit text-info"></i>',array("param"=>'class="facebox"')))?>
						<?php endif?>  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_report/property/paymentcollection','ref'=>array('f_property'=>$property['prop_id']),'label'=>'<i class="glyphicon glyphicon-tasks text-info"></i>',array("param"=>'wide_opener')))?>  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_property/master/edit','ref'=>$encPropId,'label'=>'<i class="glyphicon glyphicon-edit text-info"></i>',array("param"=>'class="facebox"')))?>  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_property/master/view','ref'=>$encPropId,'label'=>'<i class="glyphicon glyphicon-search text-info"></i>'))?> 
					</td>
					<!--<td class="center">
						<?//=x(array('link'=>'erp_property/master/delete','ref'=>$encPropId,'label'=>'<i class="glyphicon glyphicon-trash text-danger"></i>',array("param"=>'class="facebox"')))?> 
					</td>-->
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->propertyObj->pagination();?>
	</div>
</div>

	<?=x(array('link'=>'erp_report/property/property','label'=>'
		<div class="col-md-3">
			<div class="card">
					<div class="card-block">
					<div class="card-block">
						<h4 class="card-title center">Properties</h4>
						<p class="card-text">
							<small class="text-muted"></small>
						</p>
					</div>
				</div>
			</div>
		</div>
	', array("param"=>'wide_opener')),'<br><br>')?>
	
		<?=x(array('link'=>'erp_report/property/propdocument','label'=>'
		<div class="col-md-3">
			<div class="card">
					<div class="card-block">
					<div class="card-block">
						<h4 class="card-title center">Prop Document</h4>
						<p class="card-text">
							<small class="text-muted"></small>
						</p>
					</div>
				</div>
			</div>
		</div>
	', array("param"=>'wide_opener')),'<br><br>')?>
	
	<?=x(array('link'=>'erp_report/property/propdocument','ref'=>array('ref'=>'exp'),'label'=>'
		<div class="col-md-3">
			<div class="card">
					<div class="card-block" style="background-color: ;">
					<div class="card-block">
						<h4 class="card-title center">Doc Expiry</h4>
						<p class="card-text">
							<small class="text-muted"></small>
						</p>
					</div>
				</div>
			</div>
		</div>
	', array("param"=>'wide_opener')),'<br><br>')?>
	
	<?=x(array('link'=>'erp_property/rent/propertypay','label'=>'
		<div class="col-md-3">
			<div class="card">
					<div class="card-block" style="background-color: ;">
					<div class="card-block">
						<h4 class="card-title center">Rent Schedule</h4>
						<p class="card-text">
							<small class="text-muted"></small>
						</p>
					</div>
				</div>
			</div>
		</div>
	', array("param"=>'wide_opener')),'<br><br>')?>
	
	<?=x(array('link'=>'erp_report/property/propvacant','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Property Status</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>

	<?=x(array('link'=>'erp_report/property/propertymeter','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Property Meter</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>

</form>
