<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_property/master/propdocsedit/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;" enctype="multipart/form-data">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Modify Document Details</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-2 form-control-label" >Tenant</label>
					<div class="col-sm-4">
                    <?=$this->form->agr_tenant->show()?>
                 	 </div>
					<label class="col-sm-2 form-control-label" >Agreement No.</label>
					<div class="col-sm-4">
                    <?=$this->form->docno->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Agreement Start Date</label>
					<div class="col-sm-4">
                    <?=$this->form->doi->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Agreement End Date</label>
					<div class="col-sm-4">
                    <?=$this->form->doe->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Agreement Amount</label>
					<div class="col-sm-4">
                    <?=$this->form->agr_amount->show()?>
                  </div>

					<label class="col-sm-2 form-control-label" >Rent Amount</label>
					<div class="col-sm-4">
                    <?=$this->form->agr_rent->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 form-control-label" >Payment Details</label>
					<div class="col-sm-4">
                    <?=$this->form->agr_paydet->show()?>
                  </div>
					<label class="col-sm-2 form-control-label" >Remarks</label>
					<div class="col-sm-4">
                    <?=$this->form->docremark->show()?>
                  </div>
				</div>		
			<div class="form-group row">
				<div id="" class="col-sm-3">
					<div class="">
						<label class="form-control-label">Upload Document <?=$this->form->docUpdate->show()?></label>
	                     
	                  </div>
				</div>
				<div class="col-sm-4" style="margin-left:  -80px;">
					<div id="docUpload">
                 		<?=$this->form->my_files->show()?>
                 	</div>
				</div>
			<label class="col-sm-2 form-control-label" >Alert days</label>
				<div class="col-sm-2">
                <?=$this->form->alert->show()?>
            </div>
				
			</div>
			</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Update</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>

<script type="text/javascript">           
$(document).ready(function() {
	var reload = '<?=$reload;?>';
	if(reload)
		window.location.replace(reload);
});
$('#docUpdate1').on('click',function() {
	typetoggle();
});
typetoggle();
function typetoggle(type){
	if($('#docUpdate1').prop('checked') === true)
		$('#docUpload').show();
	else
		$('#docUpload').hide();
}
</script>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '80%');
})
</script>