<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_masters/item/srvadd' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Add item</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row" style="margin-top: 15px;">
					<label class="col-sm-3 form-control-label" >Item Code</label>
					<div class="col-sm-9">
                    <?=$this->form->code->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Name</label>
					<div class="col-sm-9">
                    <?=$this->form->name->show()?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Description</label>
					<div class="col-sm-9">
                    <?=$this->form->remarks->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn  btn-success submit-alias btn-rounded livepost" >Add</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</form>	
</div>
