<div class="dynamic-popup" id="dynamic-popup">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Item Details</h4>
	</div>
	<div class="modal-body">
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Item Code</label>
					<div class="col-sm-6">
                     <?=$this->itemDetail['item_code']?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Item Name</label>
					<div class="col-sm-6">
                     <?=$this->itemDetail['item_name']?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Price</label>
					<div class="col-sm-6">
                    <?=$this->itemDetail['item_price']?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Remarks</label>
					<div class="col-sm-6">
                    <?=$this->itemDetail['item_remarks']?>
                  </div>
				</div>
				<div class="form-group row">
					<label class="col-sm-3 form-control-label" >Unit</label>
					<div class="col-sm-6">
                    <?=$this->itemDetail['item_unit']?>
                  </div>
				</div>
	</div>
	<div class="modal-footer popup-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '550px');
})
</script>
